version: '3'
services:
  pg-docker:
    image: "postgres:10"
    ports:
      - "5432:5432"
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    env_file:
      - "./postgres/postgres.env"
  api:
    build:
       context: "../api"
       dockerfile: "../docker/api/Dockerfile"
    ports:
      - "5000:5000"
    environment:
       DB_HOST: pg-docker
    env_file:
      - './api/panvala-api.env'
    tty: true
  frontend:
    build:
      context: "../client"
      dockerfile: "../docker/frontend/Dockerfile"
    ports:
      - "3001:3000"
    environment:
      API_HOST: api
